AllCops:
  Include:
    - '**/*.rb'
    - Rakefile
    - config.ru
  Exclude:
    - gems/**/*
    - db/**
    - config/**
    - script/**
  TargetRubyVersion: 3.2.2
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

Style/AccessorGrouping:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: line_count_based
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

# We don't consider .positive? etc to be that readable
Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/BlockEndNewline:
  Enabled: false

Layout/CaseIndentation:
  IndentOneStep: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Layout/LineLength:
  Max: 100

# Disabled so that we can write .to_not change { } in Rspec
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - delegate

Style/AsciiComments:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
